"""Coluna vagas adicionada em carona

Revision ID: 12fad38ff73e
Revises: d06f5a71faf1
Create Date: 2024-05-24 20:49:52.282996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fad38ff73e'
down_revision: Union[str, None] = 'd06f5a71faf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carona', sa.Column('vagas', sa.Integer(), nullable=False))
    op.drop_index('ix_carona_local_chegada', table_name='carona')
    op.create_index(op.f('ix_carona_local_destino'), 'carona', ['local_destino'], unique=False)
    op.create_index(op.f('ix_carona_vagas'), 'carona', ['vagas'], unique=False)
    op.drop_index('ix_pedido_carona_local_chegada', table_name='pedido_carona')
    op.create_index(op.f('ix_pedido_carona_local_destino'), 'pedido_carona', ['local_destino'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_carona_local_destino'), table_name='pedido_carona')
    op.create_index('ix_pedido_carona_local_chegada', 'pedido_carona', ['local_destino'], unique=False)
    op.drop_index(op.f('ix_carona_vagas'), table_name='carona')
    op.drop_index(op.f('ix_carona_local_destino'), table_name='carona')
    op.create_index('ix_carona_local_chegada', 'carona', ['local_destino'], unique=False)
    op.drop_column('carona', 'vagas')
    # ### end Alembic commands ###
