"""Coluna aceito de pedido_carona removida para refatoração

Revision ID: 12fb9b817569
Revises: 12fad38ff73e
Create Date: 2024-05-26 15:30:40.747132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12fb9b817569'
down_revision: Union[str, None] = '12fad38ff73e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pedido_carona_aceito', table_name='pedido_carona')
    op.drop_column('pedido_carona', 'aceito')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_carona', sa.Column('aceito', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_pedido_carona_aceito', 'pedido_carona', ['aceito'], unique=False)
    # ### end Alembic commands ###
