"""driver e driver_vehicle deletadas

Revision ID: 2548c731dcf5
Revises: 9578191dc473
Create Date: 2024-05-13 10:08:15.620701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2548c731dcf5'
down_revision: Union[str, None] = '9578191dc473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_driver_vehicle_fk_driver', table_name='driver_vehicle')
    op.drop_index('ix_driver_vehicle_fk_vehicle', table_name='driver_vehicle')
    op.drop_index('ix_driver_vehicle_id', table_name='driver_vehicle')
    op.drop_index('ix_driver_vehicle_plate', table_name='driver_vehicle')
    op.drop_table('driver_vehicle')
    op.drop_index('ix_driver_fk_user', table_name='driver')
    op.drop_index('ix_driver_id', table_name='driver')
    op.drop_index('ix_driver_license', table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('driver',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('license', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='driver_fk_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_pkey')
    )
    op.create_index('ix_driver_license', 'driver', ['license'], unique=True)
    op.create_index('ix_driver_id', 'driver', ['id'], unique=False)
    op.create_index('ix_driver_fk_user', 'driver', ['fk_user'], unique=True)
    
    op.create_table('driver_vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_driver', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_vehicle', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_driver'], ['driver.id'], name='driver_vehicle_fk_driver_fkey'),
    sa.ForeignKeyConstraint(['fk_vehicle'], ['vehicle.id'], name='driver_vehicle_fk_vehicle_fkey'),
    sa.PrimaryKeyConstraint('id', name='driver_vehicle_pkey')
    )
    op.create_index('ix_driver_vehicle_plate', 'driver_vehicle', ['plate'], unique=True)
    op.create_index('ix_driver_vehicle_id', 'driver_vehicle', ['id'], unique=False)
    op.create_index('ix_driver_vehicle_fk_vehicle', 'driver_vehicle', ['fk_vehicle'], unique=False)
    op.create_index('ix_driver_vehicle_fk_driver', 'driver_vehicle', ['fk_driver'], unique=False)
    # ### end Alembic commands ###
