"""Valor default da coluna aceito alterado para False

Revision ID: 30731422b256
Revises: 80784aa22b94
Create Date: 2024-05-22 22:34:55.845983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30731422b256'
down_revision: Union[str, None] = '80784aa22b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_carona', 'aceito', server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedido_carona', 'aceito', server_default=sa.text('true'))
    # ### end Alembic commands ###
