"""coluna active adicionada em motorista_veiculo

Revision ID: 447302a88d7b
Revises: 8e326fbc9f8f
Create Date: 2024-05-21 23:57:03.951482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447302a88d7b'
down_revision: Union[str, None] = '8e326fbc9f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorista_veiculo', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorista_veiculo', 'active')
    # ### end Alembic commands ###
