"""user_carona recriada para refatoracao

Revision ID: 65a8d386ffa4
Revises: 8714724a8a6a
Create Date: 2024-05-21 23:36:19.696670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a8d386ffa4'
down_revision: Union[str, None] = '8714724a8a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_carona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('fk_carona', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fk_carona'], ['carona.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_user', 'fk_carona')
    )
    op.create_index(op.f('ix_user_carona_fk_carona'), 'user_carona', ['fk_carona'], unique=False)
    op.create_index(op.f('ix_user_carona_fk_user'), 'user_carona', ['fk_user'], unique=False)
    op.create_index(op.f('ix_user_carona_id'), 'user_carona', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_carona_id'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_fk_user'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_fk_carona'), table_name='user_carona')
    op.drop_table('user_carona')
    # ### end Alembic commands ###
