"""Typo na coluna nota_pasageiro

Revision ID: 6ad2ebdd1f4c
Revises: 83c1ca77e3c7
Create Date: 2024-06-10 20:24:10.117032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad2ebdd1f4c'
down_revision: Union[str, None] = '83c1ca77e3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_carona', 'nota_pasageiro', new_column_name='nota_passageiro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_carona', 'nota_passageiro', new_column_name='nota_pasageiro')
    # ### end Alembic commands ###
