"""avaliacao

Revision ID: 80784aa22b94
Revises: eacc89ecb2bf
Create Date: 2024-05-22 19:03:51.453597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80784aa22b94'
down_revision: Union[str, None] = 'eacc89ecb2bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_carona', sa.Column('nota_motorista', sa.Float(), nullable=False))
    op.add_column('user_carona', sa.Column('nota_pasageiro', sa.Float(), nullable=False))
    op.add_column('user_carona', sa.Column('comentário_sobre_motorista', sa.String(), nullable=False))
    op.add_column('user_carona', sa.Column('comentário_sobre_passageiro', sa.String(), nullable=False))
    op.create_index(op.f('ix_user_carona_comentário_sobre_motorista'), 'user_carona', ['comentário_sobre_motorista'], unique=False)
    op.create_index(op.f('ix_user_carona_comentário_sobre_passageiro'), 'user_carona', ['comentário_sobre_passageiro'], unique=False)
    op.create_index(op.f('ix_user_carona_nota_motorista'), 'user_carona', ['nota_motorista'], unique=False)
    op.create_index(op.f('ix_user_carona_nota_pasageiro'), 'user_carona', ['nota_pasageiro'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_carona_nota_pasageiro'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_nota_motorista'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_comentário_sobre_passageiro'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_comentário_sobre_motorista'), table_name='user_carona')
    op.drop_column('user_carona', 'comentário_sobre_passageiro')
    op.drop_column('user_carona', 'comentário_sobre_motorista')
    op.drop_column('user_carona', 'nota_pasageiro')
    op.drop_column('user_carona', 'nota_motorista')
    # ### end Alembic commands ###