"""Coluna fk_carona adicionada em pedido_carona

Revision ID: 83c1ca77e3c7
Revises: 12fb9b817569
Create Date: 2024-05-26 15:32:49.058700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c1ca77e3c7'
down_revision: Union[str, None] = '12fb9b817569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_carona', sa.Column('fk_carona', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pedido_carona_fk_carona'), 'pedido_carona', ['fk_carona'], unique=False)
    op.create_foreign_key(None, 'pedido_carona', 'carona', ['fk_carona'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedido_carona', type_='foreignkey')
    op.drop_index(op.f('ix_pedido_carona_fk_carona'), table_name='pedido_carona')
    op.drop_column('pedido_carona', 'fk_carona')
    # ### end Alembic commands ###
