"""coluna created_at e updated_at adicionadas em motorista_veiculo

Revision ID: 8e326fbc9f8f
Revises: fc9bf3a13901
Create Date: 2024-05-21 23:54:41.577447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e326fbc9f8f'
down_revision: Union[str, None] = 'fc9bf3a13901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motorista_veiculo', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('motorista_veiculo', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motorista_veiculo', 'updated_at')
    op.drop_column('motorista_veiculo', 'created_at')
    # ### end Alembic commands ###
