"""Colunas de local de partida e chegada criadas

Revision ID: 8f41a43fd9f9
Revises: d6eb61b6064c
Create Date: 2024-05-23 15:21:20.957352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f41a43fd9f9'
down_revision: Union[str, None] = 'd6eb61b6064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carona', sa.Column('local_partida', sa.String(), nullable=False))
    op.add_column('carona', sa.Column('local_chegada', sa.String(), nullable=False))
    op.create_index(op.f('ix_carona_local_chegada'), 'carona', ['local_chegada'], unique=False)
    op.create_index(op.f('ix_carona_local_partida'), 'carona', ['local_partida'], unique=False)
    op.add_column('pedido_carona', sa.Column('local_partida', sa.String(), nullable=False))
    op.add_column('pedido_carona', sa.Column('local_chegada', sa.String(), nullable=False))
    op.create_index(op.f('ix_pedido_carona_local_chegada'), 'pedido_carona', ['local_chegada'], unique=False)
    op.create_index(op.f('ix_pedido_carona_local_partida'), 'pedido_carona', ['local_partida'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_carona_local_partida'), table_name='pedido_carona')
    op.drop_index(op.f('ix_pedido_carona_local_chegada'), table_name='pedido_carona')
    op.drop_column('pedido_carona', 'local_chegada')
    op.drop_column('pedido_carona', 'local_partida')
    op.drop_index(op.f('ix_carona_local_partida'), table_name='carona')
    op.drop_index(op.f('ix_carona_local_chegada'), table_name='carona')
    op.drop_column('carona', 'local_chegada')
    op.drop_column('carona', 'local_partida')
    # ### end Alembic commands ###
