"""driver.fk_user and others no longer nullable

Revision ID: 9578191dc473
Revises: b9ddf16fc7d0
Create Date: 2024-04-05 16:10:04.747217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9578191dc473'
down_revision: Union[str, None] = 'b9ddf16fc7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver', 'fk_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('driver_vehicle', 'fk_driver',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('driver_vehicle', 'fk_vehicle',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('driver_vehicle', 'fk_vehicle',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('driver_vehicle', 'fk_driver',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('driver', 'fk_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
