"""Criando_Tabela_Pedido_Carona

Revision ID: 9c70670d38a6
Revises: e4e40706dfca
Create Date: 2024-05-20 06:24:14.057514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.engine.reflection import Inspector

# revision identifiers, used by Alembic.
revision: str = '9c70670d38a6'
down_revision: Union[str, None] = 'e4e40706dfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    return table_name in inspector.get_table_names()

def upgrade():
    if not table_exists('user_carona'):
        op.create_table('user_carona',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('fk_carona', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('fk_user', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['fk_carona'], ['carona.id'], name='user_carona_fk_carona_fkey'),
        sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='user_carona_fk_user_fkey'),
        sa.PrimaryKeyConstraint('id', name='user_carona_pkey'),
        sa.UniqueConstraint('fk_carona', 'fk_user', name='user_carona_fk_carona_fk_user_key')
        )
        op.create_index('ix_user_carona_id', 'user_carona', ['id'], unique=False)
        op.create_index('ix_user_carona_fk_user', 'user_carona', ['fk_user'], unique=False)
        op.create_index('ix_user_carona_fk_carona', 'user_carona', ['fk_carona'], unique=False)

    if not table_exists('pedido_carona'):
        op.create_table('pedido_carona',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('fk_user', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('hora_partida_minima', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('hora_partida_maxima', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column('coord_partida', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('coord_destino', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='pedido_carona_fk_user_fkey'),
        sa.PrimaryKeyConstraint('id', name='pedido_carona_pkey'),
        )
        op.create_index('ix_user_carona_id', 'user_carona', ['id'], unique=False)
        op.create_index('ix_user_carona_fk_user', 'user_carona', ['fk_user'], unique=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_carona',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_carona', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fk_carona'], ['carona.id'], name='user_carona_fk_carona_fkey'),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], name='user_carona_fk_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_carona_pkey'),
    sa.UniqueConstraint('fk_carona', 'fk_user', name='user_carona_fk_carona_fk_user_key')
    )
    op.create_index('ix_user_carona_id', 'user_carona', ['id'], unique=False)
    op.create_index('ix_user_carona_fk_user', 'user_carona', ['fk_user'], unique=False)
    op.create_index('ix_user_carona_fk_carona', 'user_carona', ['fk_carona'], unique=False)
    # ### end Alembic commands ###
