"""tabelas renomeadas para pt-br

Revision ID: c89c25badffe
Revises: 41d268b81fd2
Create Date: 2024-05-13 11:33:30.197171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89c25badffe'
down_revision: Union[str, None] = '41d268b81fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.String(), nullable=False),
    sa.Column('cor', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo', 'marca', 'modelo', 'cor')
    )
    op.create_index(op.f('ix_veiculo_id'), 'veiculo', ['id'], unique=False)
    op.create_index(op.f('ix_veiculo_marca'), 'veiculo', ['marca'], unique=False)
    op.create_index(op.f('ix_veiculo_modelo'), 'veiculo', ['modelo'], unique=False)
    op.create_index(op.f('ix_veiculo_tipo'), 'veiculo', ['tipo'], unique=False)
    
    op.create_table('motorista',
    sa.Column('id_fk_user', sa.Integer(), nullable=False),
    sa.Column('num_cnh', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_fk_user')
    )
    op.create_index(op.f('ix_motorista_id_fk_user'), 'motorista', ['id_fk_user'], unique=True)
    op.create_index(op.f('ix_motorista_num_cnh'), 'motorista', ['num_cnh'], unique=True)
    
    op.create_table('motorista_veiculo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_motorista', sa.Integer(), nullable=False),
    sa.Column('fk_veiculo', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fk_motorista'], ['motorista.id_fk_user'], ),
    sa.ForeignKeyConstraint(['fk_veiculo'], ['veiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motorista_veiculo_fk_motorista'), 'motorista_veiculo', ['fk_motorista'], unique=False)
    op.create_index(op.f('ix_motorista_veiculo_fk_veiculo'), 'motorista_veiculo', ['fk_veiculo'], unique=False)
    op.create_index(op.f('ix_motorista_veiculo_id'), 'motorista_veiculo', ['id'], unique=False)
    op.create_index(op.f('ix_motorista_veiculo_placa'), 'motorista_veiculo', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_motorista_veiculo_placa'), table_name='motorista_veiculo')
    op.drop_index(op.f('ix_motorista_veiculo_id'), table_name='motorista_veiculo')
    op.drop_index(op.f('ix_motorista_veiculo_fk_veiculo'), table_name='motorista_veiculo')
    op.drop_index(op.f('ix_motorista_veiculo_fk_motorista'), table_name='motorista_veiculo')
    op.drop_table('motorista_veiculo')
    op.drop_index(op.f('ix_motorista_num_cnh'), table_name='motorista')
    op.drop_index(op.f('ix_motorista_id_fk_user'), table_name='motorista')
    op.drop_table('motorista')
    op.drop_index(op.f('ix_veiculo_tipo'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_modelo'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_marca'), table_name='veiculo')
    op.drop_index(op.f('ix_veiculo_id'), table_name='veiculo')
    op.drop_table('veiculo')
    # ### end Alembic commands ###
