"""Coluna local_chegada renomeada para local_destino

Revision ID: d06f5a71faf1
Revises: 8f41a43fd9f9
Create Date: 2024-05-23 15:53:54.351798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd06f5a71faf1'
down_revision: Union[str, None] = '8f41a43fd9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carona', 'local_chegada', new_column_name='local_destino', existing_type=sa.String(), existing_nullable=False)
    op.alter_column('pedido_carona', 'local_chegada', new_column_name='local_destino', existing_type=sa.String(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carona', 'local_destino', new_column_name='local_chegada', existing_type=sa.String(), existing_nullable=False)
    op.alter_column('pedido_carona', 'local_destino', new_column_name='local_chegada', existing_type=sa.String(), existing_nullable=False)
    # ### end Alembic commands ###
