"""Criacao tabela UserCarona

Revision ID: d2131892dc13
Revises: 1356543b2e31
Create Date: 2024-05-13 20:28:37.142407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2131892dc13'
down_revision: Union[str, None] = '1356543b2e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_carona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_carona', sa.Integer(), nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fk_carona'], ['carona.id'], ),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fk_carona', 'fk_user')
    )
    op.create_index(op.f('ix_user_carona_fk_carona'), 'user_carona', ['fk_carona'], unique=False)
    op.create_index(op.f('ix_user_carona_fk_user'), 'user_carona', ['fk_user'], unique=False)
    op.create_index(op.f('ix_user_carona_id'), 'user_carona', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_carona_id'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_fk_user'), table_name='user_carona')
    op.drop_index(op.f('ix_user_carona_fk_carona'), table_name='user_carona')
    op.drop_table('user_carona')
    # ### end Alembic commands ###
