"""Coluna valor adicionada a Carona

Revision ID: d45244af8608
Revises: c67716f007d1
Create Date: 2024-05-13 19:56:16.993236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45244af8608'
down_revision: Union[str, None] = 'c67716f007d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carona', sa.Column('valor', sa.Float(), nullable=False))
    op.create_index(op.f('ix_carona_valor'), 'carona', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carona_valor'), table_name='carona')
    op.drop_column('carona', 'valor')
    # ### end Alembic commands ###
