"""colunas de avalaicao de UserCarona agora podem ser nulas

Revision ID: d6eb61b6064c
Revises: 30731422b256
Create Date: 2024-05-23 02:05:48.528945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6eb61b6064c'
down_revision: Union[str, None] = '30731422b256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_carona', 'nota_motorista',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_carona', 'nota_pasageiro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user_carona', 'comentário_sobre_motorista',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_carona', 'comentário_sobre_passageiro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_carona', 'comentário_sobre_passageiro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_carona', 'comentário_sobre_motorista',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_carona', 'nota_pasageiro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user_carona', 'nota_motorista',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
