"""AtualizandoUserCarona

Revision ID: dd524e67d393
Revises: d2131892dc13
Create Date: 2024-05-19 20:39:46.610547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd524e67d393'
down_revision: Union[str, None] = 'd2131892dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
