"""Colunas valor e aceito adicionadas em pedido_carona

Revision ID: eacc89ecb2bf
Revises: 677c13f59871
Create Date: 2024-05-22 13:49:51.868725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacc89ecb2bf'
down_revision: Union[str, None] = '677c13f59871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido_carona', sa.Column('valor', sa.Float(), nullable=False))
    op.add_column('pedido_carona', sa.Column('aceito', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_pedido_carona_aceito'), 'pedido_carona', ['aceito'], unique=False)
    op.create_index(op.f('ix_pedido_carona_valor'), 'pedido_carona', ['valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_carona_valor'), table_name='pedido_carona')
    op.drop_index(op.f('ix_pedido_carona_aceito'), table_name='pedido_carona')
    op.drop_column('pedido_carona', 'aceito')
    op.drop_column('pedido_carona', 'valor')
    # ### end Alembic commands ###
