"""tabela pedido_carona criada

Revision ID: f64626206854
Revises: 65a8d386ffa4
Create Date: 2024-05-21 23:41:50.721416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64626206854'
down_revision: Union[str, None] = '65a8d386ffa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido_carona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_user', sa.Integer(), nullable=False),
    sa.Column('hora_partida_minima', sa.DateTime(), nullable=False),
    sa.Column('hora_partida_maxima', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fk_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_carona_fk_user'), 'pedido_carona', ['fk_user'], unique=False)
    op.create_index(op.f('ix_pedido_carona_hora_partida_maxima'), 'pedido_carona', ['hora_partida_maxima'], unique=False)
    op.create_index(op.f('ix_pedido_carona_hora_partida_minima'), 'pedido_carona', ['hora_partida_minima'], unique=False)
    op.create_index(op.f('ix_pedido_carona_id'), 'pedido_carona', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_carona_id'), table_name='pedido_carona')
    op.drop_index(op.f('ix_pedido_carona_hora_partida_minima'), table_name='pedido_carona')
    op.drop_index(op.f('ix_pedido_carona_hora_partida_maxima'), table_name='pedido_carona')
    op.drop_index(op.f('ix_pedido_carona_fk_user'), table_name='pedido_carona')
    op.drop_table('pedido_carona')
    # ### end Alembic commands ###
